In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
para =  """I have three visions for India. 
           In 3000 years of our history, people from all over the world have come and invaded us, captured our lands, conquered our minds.
           From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British, the French, the Dutch, all of them came and looted us, took over what was ours. 
           Yet we have not done this to any other nation. We have not conquered anyone. 
           We have not grabbed their land, their culture, their history and tried to enforce our way of life on them.
           Why? Because we respect the freedom of others.
           That is why my first vision is that of freedom. 
           I believe that India got its first vision of this in 1857, when we started the War of Independence. 
           It is this freedom that we must protect and nurture and build on. 
           If we are not free, no one will respect us.
           My second vision for India’s development.
           For fifty years we have been a developing nation. 
           It is time we see ourselves as a developed nation.
           We are among the top 5 nations of the world in terms of GDP.
           We have a 10 percent growth rate in most areas.
           Our poverty levels are falling.
           Our achievements are being globally recognised today. 
           Yet we lack the self-confidence to see ourselves as a developed nation, self-reliant and self-assured.
           Isn’t this incorrect?
           I have a third vision. 
           India must stand up to the world. 
           Because I believe that unless India stands up to the world, no one will respect us.
           Only strength respects strength. 
           We must be strong not only as a military power but also as an economic power. 
           Both must go hand-in-hand.
           My good fortune was to have worked with three great minds. 
           Dr. Vikram Sarabhai of the Dept. of space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
           I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
           I see four milestones in my career."""


In [11]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts([para])

In [12]:
tokenizer.word_index

{'the': 1,
 'of': 2,
 'we': 3,
 'have': 4,
 'and': 5,
 'to': 6,
 'i': 7,
 'in': 8,
 'our': 9,
 'a': 10,
 'not': 11,
 'this': 12,
 'that': 13,
 'my': 14,
 'india': 15,
 'world': 16,
 'us': 17,
 'nation': 18,
 'is': 19,
 'vision': 20,
 'must': 21,
 'are': 22,
 'as': 23,
 'three': 24,
 'for': 25,
 'all': 26,
 'them': 27,
 'was': 28,
 'their': 29,
 'respect': 30,
 'freedom': 31,
 'see': 32,
 'self': 33,
 'years': 34,
 'history': 35,
 'from': 36,
 'over': 37,
 'conquered': 38,
 'minds': 39,
 'yet': 40,
 'life': 41,
 'on': 42,
 'why': 43,
 'because': 44,
 'first': 45,
 'believe': 46,
 'it': 47,
 'no': 48,
 'one': 49,
 'will': 50,
 'ourselves': 51,
 'developed': 52,
 'up': 53,
 'only': 54,
 'strength': 55,
 'power': 56,
 'hand': 57,
 'worked': 58,
 'with': 59,
 'great': 60,
 'dr': 61,
 'visions': 62,
 '3000': 63,
 'people': 64,
 'come': 65,
 'invaded': 66,
 'captured': 67,
 'lands': 68,
 'alexander': 69,
 'onwards': 70,
 'greeks': 71,
 'turks': 72,
 'moguls': 73,
 'portuguese': 74,
 'british'

In [21]:
for sentences in para.split('\n'):
    print(tokenizer.texts_to_sequences([sentences]))

[[7, 4, 24, 62, 25, 15]]
[[8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5, 66, 17, 67, 9, 68, 38, 9, 39]]
[[36, 69, 70, 1, 71, 1, 72, 1, 73, 1, 74, 1, 75, 1, 76, 1, 77, 26, 2, 27, 78, 5, 79, 17, 80, 37, 81, 28, 82]]
[[40, 3, 4, 11, 83, 12, 6, 84, 85, 18, 3, 4, 11, 38, 86]]
[[3, 4, 11, 87, 29, 88, 29, 89, 29, 35, 5, 90, 6, 91, 9, 92, 2, 41, 42, 27]]
[[43, 44, 3, 30, 1, 31, 2, 93]]
[[13, 19, 43, 14, 45, 20, 19, 13, 2, 31]]
[[7, 46, 13, 15, 94, 95, 45, 20, 2, 12, 8, 96, 97, 3, 98, 1, 99, 2, 100]]
[[47, 19, 12, 31, 13, 3, 21, 101, 5, 102, 5, 103, 42]]
[[104, 3, 22, 11, 105, 48, 49, 50, 30, 17]]
[[14, 106, 20, 25, 107, 108]]
[[25, 109, 34, 3, 4, 110, 10, 111, 18]]
[[47, 19, 112, 3, 32, 51, 23, 10, 52, 18]]
[[3, 22, 113, 1, 114, 115, 116, 2, 1, 16, 8, 117, 2, 118]]
[[3, 4, 10, 119, 120, 121, 122, 8, 123, 124]]
[[9, 125, 126, 22, 127]]
[[9, 128, 22, 129, 130, 131, 132]]
[[40, 3, 133, 1, 33, 134, 6, 32, 51, 23, 10, 52, 18, 33, 135, 5, 33, 136]]
[[137, 12, 138]]
[[7, 4, 10, 139, 20]]
[[15

In [18]:
# Representing sentences into numbers sequences

input_sequences = []
for sentences in para.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentences])[0]
    
    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

In [19]:
input_sequences

[[7, 4],
 [7, 4, 24],
 [7, 4, 24, 62],
 [7, 4, 24, 62, 25],
 [7, 4, 24, 62, 25, 15],
 [8, 63],
 [8, 63, 34],
 [8, 63, 34, 2],
 [8, 63, 34, 2, 9],
 [8, 63, 34, 2, 9, 35],
 [8, 63, 34, 2, 9, 35, 64],
 [8, 63, 34, 2, 9, 35, 64, 36],
 [8, 63, 34, 2, 9, 35, 64, 36, 26],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5, 66],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5, 66, 17],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5, 66, 17, 67],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5, 66, 17, 67, 9],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5, 66, 17, 67, 9, 68],
 [8, 63, 34, 2, 9, 35, 64, 36, 26, 37, 1, 16, 4, 65, 5, 66, 17, 67, 9, 68, 38],
 [8,
  63,
  34,
  2

In [23]:
# Exacting max length of sequence in a sentence

max_len = max([len(x) for x in input_sequences])

In [24]:
# Applying Padding
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [25]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,   7,   4],
       [  0,   0,   0, ...,   7,   4,  24],
       [  0,   0,   0, ...,   4,  24,  62],
       ...,
       [  0,   0,   0, ..., 174, 175,   8],
       [  0,   0,   0, ..., 175,   8,  14],
       [  0,   0,   0, ...,   8,  14, 176]])

In [27]:
X = padded_input_sequences[:,:-1]

array([[  0,   0,   0, ...,   0,   0,   7],
       [  0,   0,   0, ...,   0,   7,   4],
       [  0,   0,   0, ...,   7,   4,  24],
       ...,
       [  0,   0,   0, ...,  32, 174, 175],
       [  0,   0,   0, ..., 174, 175,   8],
       [  0,   0,   0, ..., 175,   8,  14]])

In [35]:
X.shape

(321, 28)

In [33]:
y = padded_input_sequences[:,-1]

array([  4,  24,  62,  25,  15,  63,  34,   2,   9,  35,  64,  36,  26,
        37,   1,  16,   4,  65,   5,  66,  17,  67,   9,  68,  38,   9,
        39,  69,  70,   1,  71,   1,  72,   1,  73,   1,  74,   1,  75,
         1,  76,   1,  77,  26,   2,  27,  78,   5,  79,  17,  80,  37,
        81,  28,  82,   3,   4,  11,  83,  12,   6,  84,  85,  18,   3,
         4,  11,  38,  86,   4,  11,  87,  29,  88,  29,  89,  29,  35,
         5,  90,   6,  91,   9,  92,   2,  41,  42,  27,  44,   3,  30,
         1,  31,   2,  93,  19,  43,  14,  45,  20,  19,  13,   2,  31,
        46,  13,  15,  94,  95,  45,  20,   2,  12,   8,  96,  97,   3,
        98,   1,  99,   2, 100,  19,  12,  31,  13,   3,  21, 101,   5,
       102,   5, 103,  42,   3,  22,  11, 105,  48,  49,  50,  30,  17,
       106,  20,  25, 107, 108, 109,  34,   3,   4, 110,  10, 111,  18,
        19, 112,   3,  32,  51,  23,  10,  52,  18,  22, 113,   1, 114,
       115, 116,   2,   1,  16,   8, 117,   2, 118,   4,  10, 11

In [36]:
y.shape

(321,)

In [34]:
len(tokenizer.word_index)

176

In [38]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes = 177)

In [39]:
y.shape

(321, 177)

# Model Building

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [43]:
model = Sequential()

model.add(Embedding(177, 100, input_length=28))
model.add(LSTM(150))
model.add(Dense(177, activation='softmax'))

In [44]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 28, 100)           17700     
                                                                 
 lstm_1 (LSTM)               (None, 150)               150600    
                                                                 
 dense_1 (Dense)             (None, 177)               26727     
                                                                 
Total params: 195027 (761.82 KB)
Trainable params: 195027 (761.82 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [46]:
model.fit(X,y, epochs = 100)

Epoch 1/100


11/11 [==============================] - 5s 37ms/step - loss: 5.1680 - accuracy: 0.0405
Epoch 2/100
11/11 [==============================] - 0s 36ms/step - loss: 5.0141 - accuracy: 0.0530
Epoch 3/100
11/11 [==============================] - 0s 36ms/step - loss: 4.8931 - accuracy: 0.0498
Epoch 4/100
11/11 [==============================] - 0s 35ms/step - loss: 4.8587 - accuracy: 0.0467
Epoch 5/100
11/11 [==============================] - 0s 35ms/step - loss: 4.8294 - accuracy: 0.0530
Epoch 6/100
11/11 [==============================] - 0s 34ms/step - loss: 4.8093 - accuracy: 0.0530
Epoch 7/100
11/11 [==============================] - 0s 33ms/step - loss: 4.7927 - accuracy: 0.0561
Epoch 8/100
11/11 [==============================] - 0s 33ms/step - loss: 4.7772 - accuracy: 0.0530
Epoch 9/100
11/11 [==============================] - 0s 35ms/step - loss: 4.7600 - accuracy: 0.0467
Epoch 10/100
11/11 [==============================] - 0s 33ms/step - loss: 4.7092 - accuracy: 0.05

# Prediction

In [59]:
text = 'people from all'

for i in range(5):
   # tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
   # padding
    padded_token_text = pad_sequences([token_text], maxlen = 28, padding='pre')
   # predict 
    position = np.argmax(model.predict(padded_token_text))

    for word,index in tokenizer.word_index.items():
        if index == position:
            text = text + " " + word
            print(text)    
    

1/1 [==============================] - 0s 56ms/step
people from all onwards
1/1 [==============================] - 0s 56ms/step
people from all onwards the
1/1 [==============================] - 0s 61ms/step
people from all onwards the greeks
1/1 [==============================] - 0s 60ms/step
people from all onwards the greeks the
1/1 [==============================] - 0s 57ms/step
people from all onwards the greeks the turks


In [55]:
print(padded_token_text)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0 15]]
